### ISSUE TITLE
Causallib installation on Python 3.12 

### ISSUE THREAD

**Issue by JuliusKumar** [BiomedSciAI/causallib#70] opened 2024-07-12 23:08 UTC
Hello
Causallib does not install on Python 3.12. 
it appears that python 3.12 removed support for 'distutils' and causallib is looking for this module

**Comment by yishaishimoni** [comment] 2024-07-14 15:36
causallib doesn't require disutils directly, and the issue is through scikit-learn 1.1.3, since causallib does require scikit-learn<1.2. 
Upgrading to scikit-learn 1.2 or higher will require some additional work as they completely changed the way they deal with labeled arrays, and causallib needs to somehow wrap a and X in a way it can then separate back. 
Until this is fixed I recommend marking explicitly that causallib only supports python<3.12.
I also recommend closing this issue and adding this implication as a comment for the issue for bumping up support for scikit-learn

**Comment by ehudkr** [comment] 2024-07-21 09:10
Thanks Yishai, there's no way I know of to make this limitation more intelligible, and I agree the proper way to close this issue is to properly support scikit-learn>=1.2.

**Closed by ehudkr** 2024-07-21 09:10 UTC
